module.exports = {
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  CREATE_USER: 'CREATE_USER',
  VERIFY_USER: 'VERIFY_USER',
  CHESS_MOVE: 'CHESS_MOVE'
};